//
// Created by Nathan on 01/09/2024.
//
#ifndef WAKUPATOR_CORE_H
#define WAKUPATOR_CORE_H

#include <stdint.h>

#include "wakupator/core/client.h"

typedef enum WAKUPATOR_CODE {
    OK = 0,
    OUT_OF_MEMORY,

    //System error (Initialisation of Wakupator)
    INIT_MUTEX_CREATION_ERROR,
    INIT_PIPE_CREATION_ERROR,
    INIT_RAW_SOCKET_CREATION_ERROR,
    INIT_INTERFACE_GATHER_IF_INDEX_ERROR,
    INIT_INTERFACE_GATHER_IF_MAC_ERROR,

    //Parsing error
    PARSING_CJSON_ERROR,
    PARSING_INVALID_MAC_ADDRESS,
    PARSING_INVALID_NAME_FORMAT,
    PARSING_INVALID_NAME_TOO_LONG,
    PARSING_INVALID_SHUTDOWN_TIME_FORMAT,
    PARSING_INVALID_IP_ADDRESS,
    PARSING_DUPLICATED_IP_ADDRESS,
    PARSING_INVALID_PORT,

    //Manager error
    MANAGER_MAC_ADDRESS_ALREADY_MONITORED,
    MANAGER_THREAD_CREATION_ERROR,
    MANAGER_THREAD_INIT_TIMEOUT,
    MANAGER_THREAD_INIT_ERROR,
    MANAGER_IP6_NOT_AVAILABLE,

    //Thread monitor error
    MONITOR_DAD_ERROR, //Duplicate Addr Detection
    MONITOR_CHECK_IP_ERROR,
    MONITOR_RAW_SOCKET_CREATION_ERROR,
    MONITOR_IP_ALREADY_USED

} WAKUPATOR_CODE;

const char* get_wakupator_message_code(WAKUPATOR_CODE code);

#endif //WAKUPATOR_CORE_H
